### ISSUE TITLE
Downloaded video auto stop after playing (crypt key received slowly error)

### ISSUE THREAD

**Issue by bacfabbi** [Cyklet/VidLoader#35]
After downloaded video. I play that video. The video auto stop after ~2minutes. I can't restart with start/stop button press.
**Video Information:**
+ Duration: 2h:19m:45s
+ URL: https://www2.uliza.jp/IF/iphone/iPhonePlaylist.m3u8?v=142485-627600&p=3006&d=629&n=1698&t=c961aee9dd1441b7a9a3ff4d4df54179&maxbit=2000&minbit=364&previewflag=0
OS version: 12.5.5
Error Log:
```
#Version: 1.0
#Software: AppleCoreMedia/1.0.0.16H62 (iPhone; U; CPU OS 12_5_5 like Mac OS X; en_us)
#Date: 2022/04/07 14:25:37.037
#Fields: date time uri cs-guid s-ip status domain comment cs-iftype
2022/04/07 14:25:26.026 vidloader-encryption-key:A/aHwB228+xfrpI3CC1DUg==0 CA14A368-AB0A-4A72-8528-D102648BCB8A - -16833 "CoreMediaErrorDomain" "crypt key received slowly" unknown
2022/04/07 14:25:37.037 vidloader-encryption-key:A/aHwB228+xfrpI3CC1DUg==0 CA14A368-AB0A-4A72-8528-D102648BCB8A - -16833 "CoreMediaErrorDomain" "crypt key received slowly" unknown
)
```
Error video evidence:
https://user-images.githubusercontent.com/87011739/162150873-5d84294c-5e42-46c5-a920-98a9cb3d90f9.mp4
I think that it has a problem with loading encryption key from local. But don't know to fix. Please help me.

**Comment by Cyklet** [comment]
Hi @bacfabbi the encryption key is not loaded from file, it comes together with chunks so there is low chances of timeout during this phase.
Can you please share the encryption key URL or m3u8 playlists (the provided url is expired), it seems that SchemeType vidloader-encryption-key was parsed wrongly:
`vidloader-encryption-key:A/aHwB228+xfrpI3CC1DUg==0` it looks like a wrong key syntax and it can't be used in the next iteration so most probably the play is failing because of that. The correct one should look like: `vidloader-encryption-key://aHwB228+xfrpI3CC1DUg==0` that after `:` has `//` instead of `A/`

**Comment by bacfabbi** [comment]
@Cyklet 
Thanks for your responding
The new url: https://www2.uliza.jp/IF/iphone/iPhonePlaylist.m3u8?v=142485-627600&p=3006&d=629&n=1698&t=4cca6e937c02baf48a670f624ea7b8e0&maxbit=2000&minbit=364&previewflag=0

**Comment by bacfabbi** [comment]
@Cyklet 
I send the encryption key URL
vidloader-encryption-key:aHkxaYVc5Kz+/EvgT+fizw==

**Comment by Cyklet** [comment]
Issue is located in 
```
private func replacePaths(response: String,
                              with baseURL: URL,
                              completion: @escaping (Result<Data, M3U8Error>) -> Void)
```
`result.replacingOccurrences` is replacing keys of chunks that contain the same numbers:
example:
`key for time 77 is replacing key path for 77 and also for 177 too`
